config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new'
  end

  post "new/note" => "notes#new_note", constraints: {xhr?: true}
  delete "delete/note/:id" => "notes#delete_note", as: "delete_note"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :notes
  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @notes = Note.all
    if @notes.length == 0 and !user_signed_in?
      redirect_to login_path
    end
  end

  def new_note
    values = new_note_safe_params
    unless values.blank?
      note = current_user.notes.create(values)
      if note.persisted?
        message = "Note Created successfully."
        status = :created
      else
        message = note.errors.full_messages.to_sentence
        status = :unprocessible_entity
      end
    end
    respond_to do |format|
      format.json { render json: message.to_json, status: status }
    end
  end

  def delete_note
    unless params[:id].blank?
      note = current_user.notes.find(params[:id])
      unless note.blank?
        record = note.destroy
        if record.destroyed?
          flash[:info] = "Note deleted"
        end
        redirect_to root_path
      end
    end
  end

  private

  def new_note_safe_params
    params.require(:note).permit(:title, :body, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <meta http-equiv="cache-control" content="no-cache"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-md fixed-top">
      <%= link_to("Notes App", root_path , :class => "navbar-brand mr-auto") %>
      <% if user_signed_in? %>
        <div class="profile_details btn-group btn-group-sm" role="group" aria-label="Basic example">
          <span class="btn"><i class="fa fa-user"></i></span>
          <span class="btn"><%= current_user.name %> <span class="d-none d-sm-block">(<%= current_user.email %>)</span></span>
          <%= link_to("Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary") %>
        </div>
      <% else %>
        <%= link_to("Login", login_path, class: "btn btn-primary btn-sm") %>
      <% end %>
    </nav>
  </header>

  <main class="container">
    <%= yield %>
  </main>
  <%= yield(:modals) %>
</body>
</html>

app/views/notes/index.html.erb
<%= content_for :title, "Home" %>
<div class="row no-padding-margin notes_list_card">
  <% flash.each do |flash_type, message| %>
    <div class="col-sm-12 mb-2">
      <div class="alert <%= (flash_type == 'danger') || (flash_type == 'alert') ? 'alert-secondary' : 'alert-success' %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>
  <% unless @notes.blank? %>
    <% @notes.each do |note| %>
      <div class="col-sm-4 mb-4">
        <div class="card note_card" data-title="<%= note.title %>" data-body="<%= note.body %>" data-tags="<%= note.tag_list %>">
          <div class="card-body">
            <% if user_signed_in? and (current_user == note.user) %>
              <%= link_to("×", delete_note_path(note.id), data: {confirm: "are you sure?"}, method: :delete, class: "del_note") %>
            <% end %>
            <span class="card-title"><%= note.title %></span>
            <p class="note-body"><%= note.body %></p>
            <% note.tag_list.first(2).each do |tag| %>
              <span class="note_tag"><%= tag %></span>
            <% end %>
            <% if (note.tag_list.length - 2) > 0 %>
              <span class="note_tag">+ <%= note.tag_list.length - 3 %> more</span>
            <% end %>
          </div>
          <div class="card-footer">
            By <%= note.user.name %> <span class="text-muted pull-right"><%= time_ago_in_words(note.created_at) %> ago</span>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <div class="col-sm-12 col-md-3 col-lg-3">
      <div class="card addNewNoteCard">
        <div class="card-body">
          <a href="javascript:void(0)" class="addNotes" data-toggle="modal" data-target="#newNoteModal">
            <i class="fa fa-plus"></i>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% content_for :modals do %>
  <% if user_signed_in? %>
    <div class="modal fade" id="newNoteModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <div class="modal-title">New Note</div>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">Close</span>
            </button>
          </div>
          <%= form_for current_user.notes.new, url: new_note_path, method: :post, remote: true, html: { class: "newNoteForm" } do |f| %>
            <div class="modal-body">
              <div class="customisedForm">
                <div class="form-group">
                  <%= f.label :title %>
                  <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
                </div>
                <div class="form-group">
                  <%= f.label :body %>
                  <%= f.text_area :body, class: "form-control", placeholder: "Type the body of the note." %>
                </div>
                <div class="form-group">
                  <%= f.label :tag_list, "Tags" %>
                  <%= f.text_field :tag_list, data: {role: "tagsinput"} %>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <%= f.submit "Save", class: "btn btn-sm btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="modal fade" id="notesDetailsModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-title">Note Details</div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="customisedForm">
            <div class="form-group">
              <span class="heading">Title</span>
              <span class="details title"></span>
            </div>
            <div class="form-group">
              <span class="heading">Body</span>
              <span class="details body"></span>
            </div>
            <div class="form-group">
              <span class="heading">Tags</span>
              <div class="details tags">
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>